### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by patdflynn** [CODEJIN/Glow_TTS#5]
Hello, I'm new to your repo and I'm not sure how to inference. I see there are instructions to train and that there's some text files for inferences already in the repo, I'm fine with benchmarking with those. I'm using the LUT approach with your pretrained checkpoints.

**Comment by CODEJIN** [comment]
Hi, you are right. I forgot the inference code... Current results were extracted while model trained.  I will added the inference code soon. Thank you!

**Comment by CODEJIN** [comment]
Hi, I uploaded two inference example files: [Inference_Example.ipynb](Inference_Example.ipynb) and [Inference.py](Inference.py). Please check them.

Thanks,

Heejo

**Comment by patdflynn** [comment]
Thank you!
